### ISSUE TITLE
Placeholder for cameras locations on maps (with their specs) is missing 

### ISSUE THREAD

**Issue by VincGargasson** [pyronear/pyronear-webapp#4]
The creation of a workflow to collect, process and display the data on the map is needed here. 
As long as we don't have the real data, let's create the function and placeholder in order to incorporate the real data later.

**Comment by nrslt** [comment]
thinking one step ahead, nice!

**Comment by pechouc** [comment]
Oops, just saw that I had missed this issue!

I was wondering if we could not reuse the information box in the upper right of the map to display essential data about the camera and then, reveal more if the user clicks on the marker? 

Let me explain a bit better: 

If the user simply hovers the marker, we could display for instance the name of the camera (which basically corresponds to the infrastructure on which it is located for now), its coordinates and its status (alert or not) in the information box here:

![95656347-20a40580-0b0e-11eb-9b02-b5d97abcaee1](https://user-images.githubusercontent.com/63041127/96089048-90c3da00-0ec6-11eb-886e-e41bb8e146e3.png)

And then, once users know that they have found the camera they were looking for, they can click on the marker to get more information in a separate object (last alert, orientation, possibly last captured image...).

Just an idea but let me know what you think of this 😊

**Comment by VincGargasson** [comment]
I'm note very good at UX but it's an interesting suggestion @pechouc. 
As the data will maybe take a few second to display and will take place with the popup, your idea might solve this UX issue. 
Will push this in my PR ;)
